### ISSUE TITLE
Downloader max_score doesn't work if submissions aren't done yet before running script

### ISSUE THREAD

**Issue by omar2535** [CybercentreCanada/assemblyline-incident-manager#7]
Downloader has an interesting case where the `max_score` doesn't work if the submissions jobs aren't done yet. Can be replicated by chaining the `submitter` -> `downloader` in a script and filtering for a max score where some files have a higher score and some files have a lower score. All files that were submitted in the job will be downloaded even though some files were clearly above the `max_score`

- Seems to be because the script is making a query before waiting for all submissions are complete, then the script proceeds to download all files that were queried in the original query. However, a score for a submission isn't valid until the submission is complete.

Maybe it might be better to wait for all submissions to complete before making the query?

**Comment by cccs-kevin** [comment]
@omar2535  I was unable to reproduce the scenario you describe, so can you confirm that the linked PR for this issue is the solution?

**Comment by omar2535** [comment]
Tried it with the new PR and didn't seem to fix the issue. I can see now that submissions are complete, but the `max_score` sometimes shows 10 while other times it shows 0. Always though, the score will be 10 if I do a `sleep` for long enough. The file I'm using to test is this btw: https://github.com/pentestmonkey/php-reverse-shell/blob/master/php-reverse-shell.php

See below for screenshots:
Run with max score working:
![image](https://user-images.githubusercontent.com/9442294/171005028-b5098e61-93be-4523-8e4d-5ae2750302a6.png)

Run with max score not working:
![image](https://user-images.githubusercontent.com/9442294/171005097-1815acd7-f1d5-42f7-a71e-e8a4357468df.png)

Code used:

```py
        print(f"SID: {sids}")
        print(f"sha256: {al_client.submission(sid)['files'][0]['sha256']}")
        print(f"Is complete: {al_client.submission.is_completed(sid)}")
        for sub in al_client.search.stream.submission(sid, fl="max_score"):
            print(f"Max score: {sub['max_score']}")
```

## Alternative?
I then did a comparison of the max score via the `al_client.search.stream` method vs taking `al_client.submission(sid)['max_score']` and found that the latter always gives the correct score. Shown below:
![image](https://user-images.githubusercontent.com/9442294/171005950-419d2fb8-9b2a-4107-8b41-428961584d83.png)

Code I used:

```py
        print(f"Is complete: {al_client.submission.is_completed(sid)}")
        print(f"SID: {sids}")
        print(f"sha256: {al_client.submission(sid)['files'][0]['sha256']}")
        print(f"max_score1: {al_client.submission(sid)['max_score']}")
        for sub in al_client.search.stream.submission(sid, fl="max_score"):
            print(f"max_score2: {sub['max_score']}")
```

**Comment by cccs-kevin** [comment]
Thanks for the information. I added this commit https://github.com/CybercentreCanada/assemblyline-incident-manager/pull/8/commits/0c9a0ddd6707fc3d5aa7a3af1c7d438c979cce35 to the PR. Let me know if that works :)

**Comment by omar2535** [comment]
Looks good! Works now! Thanks for being so responsive on this
